### ISSUE TITLE
RightMenu doesn't span full, modified menuWidth

### ISSUE THREAD

**Issue by CompassCanJV** [apploft/APLSlideMenu#21]
I've tried implementing a rightMenu and it works, however when I change the menuWidth the visible frame of the RightMenu doesn't change and the additional space seems to be taken up by the leftMenu.

For example: I modified my menuWidth to (self.view.frame.size.width - 30), and although it works for LeftMenu, it isn't working for RightMenu.

**Comment by CompassCanJV** [comment]
I figured it out...

    - (void)setRightMenuViewController:(UIViewController *)menuViewController {
    
    if (_rightMenuViewController) {
        [_rightMenuViewController willMoveToParentViewController:nil];
        [_rightMenuViewController.view removeFromSuperview];
        [_rightMenuViewController removeFromParentViewController];
    }
    
    _rightMenuViewController = menuViewController;
    if (menuViewController) {
        UIView *menuView    = menuViewController.view;
        menuView.accessibilityElementsHidden = YES;
        CGRect menuFrame = self.view.bounds;
        menuFrame.size.width = self.menuAbsoluteWidth + kAPLSlideMenuFirstOffset;
        menuFrame.origin.x = self.view.bounds.size.width - menuFrame.size.width;
        
        menuView.frame = menuFrame;
        menuView.autoresizingMask = UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleHeight;
        
        [self addChildViewController:menuViewController];
        [self.view insertSubview:menuView atIndex:0];
        
        [menuViewController didMoveToParentViewController:self];
    }
    }

This is the only spot the rightMenu's frame is being assigned. It's origin isn't being modified anywhere else in the code. So when I change the menuWidth anywhere that isn't the appDelegate, the frame stays in the default position and the additional space made from increasing the menuWidth is taken up by the leftMenu.

I don't want to **have** to assign the width from the AppDelegate.

**Comment by michaelkamphausen** [comment]
You are right, there is a bug. The menuWidth setter adjusts the width of the rightMenuViewController, but not the origin along the x-axis accordingly. I pushed a fix. Does it solve your problem?

**Comment by CompassCanJV** [comment]
Problem fixed, thanks a lot!
