### ISSUE TITLE
Menu Closes on iPad in Landscape

### ISSUE THREAD

**Issue by raginggoat** [apploft/APLSlideMenu#23]
I am switching the contentViewController when a row is selected in my left menu. If the app is in portrait, the left menu should close, and it does. When in landscape,  the left menu should stay open, but it closes and leaves me with a black bar on the right side of the screen.

![simulator screen shot feb 8 2016 11 31 45 am](https://cloud.githubusercontent.com/assets/4974456/12891887/99655224-ce57-11e5-948c-e4ebac155855.png)
![simulator screen shot feb 8 2016 11 31 51 am](https://cloud.githubusercontent.com/assets/4974456/12891896/a2911a86-ce57-11e5-9f20-7ba1189701ee.png)

```
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
    if (indexPath.row == 0) {
        FirstViewController *fvc = [[FirstViewController alloc]initWithNibName:@"FirstViewController" bundle:nil];
        UINavigationController *navController = [[UINavigationController alloc]initWithRootViewController:fvc];
        navController.delegate = dvc;
        self.slideMenuController.contentViewController = navController;

        if (UIDeviceOrientationIsPortrait([[UIDevice currentDevice]orientation])) {
            [self.slideMenuController hideMenu:YES];
        }
    } else {
        SecondViewController *svc = [[SecondViewController alloc]initWithNibName:@"SecondViewController" bundle:nil];
        UINavigationController *navController = [[UINavigationController alloc]initWithRootViewController:svc];
        navController.delegate = sac;
        self.slideMenuController.contentViewController = navController;

        if (UIDeviceOrientationIsPortrait([[UIDevice currentDevice]orientation])) {
            [self.slideMenuController hideMenu:YES];
        }
    }
}
```

**Comment by michaelkamphausen** [comment]
I cannot reproduce your problem. How are the properties of your APLSlideMenuViewController configured? Are you using a specific iOS version or a specific iPad simulator?

**Comment by mrigo** [comment]
I've the same problem.
To reproduce you must not have a rightMenuViewController.
I think it's related to APLSlideMenuController.m line 361:
```
if (self.activeMenuViewController == self.rightMenuViewController) {
        currentFrame.origin.x = -currentFrame.size.width;
    } else {
        currentFrame.origin.x = currentFrame.size.width;
    }
```
If you set `slideViewController.showLeftMenuInLandscape = YES;` in your AppDelegate, no right menu and the ipad start in LandScapemode, the activeMenuViewController is equal to nil, like self.righMenuViewController, so the frame origin x is calculated wrong.

**Comment by mrigo** [comment]
Also the property `isMenuViewVisible` it's wrongly set to NO when start in landscape mode with leftMenu open by `showLeftMenuInLandscape = YES;`.
